v1 = input('digite uma variável qualquer')
print('O tipo primitivo desse valor é{}'.format(type(v1)))
print('Só tem espaços? {}' .format(v1.isspace()))
print('É um número? {}'.format(v1.isnumeric()))
print('É alfabético? {}'.format(v1.isalpha()))
print('É alfanumérico? {}'.format(v1.isalnum()))
print('Está em letras minúsculas? {}'.format(v1.isupper()))
print('Está em letras maiusculas? {}'.format(v1.islower()))
print('Está capitalizada? {}'.format(v1.istitle()))